### ISSUE TITLE
Use `url()` with SVG images

### ISSUE THREAD

**Issue by awcrotwell** [glromeo/esbuild-sass-plugin#77]
I have been trying for a few days and can't seem to figure this one out. I have gone up and down the docs for this plugin & svgr and cannot figure it. I apologize if there is a simple solution or if this problem is out of scope of `esbuild-sass-plugin`.

Everything I try ends up with the same error:

```sh
Error: Build failed with 1 error:
../assets/stylesheets/application.scss:6470:20: ERROR: Cannot use "../assets/images/logo-mono.svg" as a URL
    at failureErrorWithLog (/workspace/node_modules/esbuild/lib/main.js:1603:15)
    at /workspace/node_modules/esbuild/lib/main.js:1249:28
    at runOnEndCallbacks (/workspace/node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (/workspace/node_modules/esbuild/lib/main.js:1247:7)
    at /workspace/node_modules/esbuild/lib/main.js:1356:14
    at /workspace/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/workspace/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/workspace/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
 {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Cannot use "../assets/images/logo-mono.svg" as a URL'
    }
  ],
  warnings: []
}
```

The actual line is `background-image: url(@img/logo-mono.svg);`.

Current Esbuild config:

```js
/* eslint-disable import/no-extraneous-dependencies */

const path = require('path');
const ImportGlobPlugin = require('esbuild-plugin-import-glob').default;
const svgrPlugin = require('esbuild-plugin-svgr');
const coffeeScriptPlugin = require('esbuild-coffeescript');
const sassPlugin = require('esbuild-sass-plugin').default;
const inlineImage = require('esbuild-plugin-inline-image');

const esbuild = require('esbuild');

const cwd = (pathname) => path.join(process.cwd(), pathname);

esbuild.build({
  entryPoints: ['application.js', 'react.js'], // TODO: Iterate on dir
  bundle: true,
  define: { // https://esbuild.github.io/api/#define
    process: '{"browser":null,"env":{"NODE_ENV":"development"}}', // TODO: Capture actual env
    global: 'window',
  },
  outdir: cwd('app/assets/builds'),
  absWorkingDir: cwd('app/javascript'),
  watch: true, // TODO: false in prod
  minify: false, // TODO: true in prod
  sourcemap: true,
  logLevel: 'debug', // TODO: Remove after regression testing
  external: ['fs', 'fs/promises', 'process', 'fs-extra'],
  tsconfig: cwd('tsconfig.json'),
  loader: {
    '.js': 'jsx',
    '.svg': 'file', // TODO: file? dataurl? text????
  },
  plugins: [
    svgrPlugin(), // Svg images
    sassPlugin({
      // importMapper: (pathname) => pathname.replace(/^@img\//, './assets/images/'),
      transform: async (rawSource, resolveDir) => {
        // TODO: Still working here, definitely not finalized
        const source = rawSource.replace(/@img/, path.resolve(__dirname, 'app/assets/images/'));

        const re = /url\(.*.svg\)/gm;
        const svgPaths = source.match(re);
        if (svgPaths === null) return source;

        console.log(source.match(re));
        // console.log(resolveDir);
        return source;
      },
    }),
    ImportGlobPlugin(), // Import with glob support (`/**/*.coffee`)
    coffeeScriptPlugin(), // Transpile CoffeeScript - TODO: Remove after permanently transpiling CoffeeScript
    inlineImage(), // Add support for other, non SVG, images.
  ],
}).catch((err) => {
  console.log(err); // eslint-disable-line no-console
  process.exit(1);
});
```

I am porting over a legacy Rails build system to Esbuild. There are plenty of things to get done but I think the config should be fleshed out enough for us to look at this problem.

Please let me know if you require any other information.

**Comment by awcrotwell** [comment]
Thanks for getting back to me so quickly Gianluca. 

Is this something that should just work™? I have tried with absolute paths like so:
![Screen Shot 2022-04-07 at 7 07 02 AM](https://user-images.githubusercontent.com/49383564/162218751-986ab527-20ab-47fa-bf83-9daf62002dd0.png)

```css
background-image: url(/workspace/app/assets/images/logo-mono.svg);
```

```sh
✘ [ERROR] Cannot use "../assets/images/logo-mono.svg" as a URL

    ../assets/stylesheets/application.scss:6470:20:
      6470 │   background-image: url(/workspace/app/assets/images/logo-mono.svg);
           ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error
[watch] build finished, watching for changes...
Error: Build failed with 1 error:
../assets/stylesheets/application.scss:6470:20: ERROR: Cannot use "../assets/images/logo-mono.svg" as a URL
    at failureErrorWithLog (/workspace/node_modules/esbuild/lib/main.js:1603:15)
    at /workspace/node_modules/esbuild/lib/main.js:1249:28
    at runOnEndCallbacks (/workspace/node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (/workspace/node_modules/esbuild/lib/main.js:1247:7)
    at /workspace/node_modules/esbuild/lib/main.js:1356:14
    at /workspace/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/workspace/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/workspace/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
 {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Cannot use "../assets/images/logo-mono.svg" as a URL'
    }
  ],
  warnings: []
}
```

However, if I change the absolute path to end with `tick.png` instead of the SVG, everything works as expected. 

I don't believe this is a path issue but I will most definitely try your recommendation a bit later today.

**Comment by awcrotwell** [comment]
For anyone that comes across this, yes it is suppose to 'just work™'. This error wasn't caused by the sass plugin but from `svgr`. The solution was to ensure the sass plugin ran before svgr like so:

```js
loader: {
    '.js': 'jsx',
    '.svg': 'dataurl',
  },
  plugins: [
    sassPlugin({}),
    svgrPlugin(), // Svg images
  ],
```

My apologies @glromeo for the issue.

**Comment by ethaning** [comment]
I had similar issues. I managed to resolve by loading svgs with the `file` loader, instead of the `dataurl` loader.
